mineral_catalog/mineral_catalog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from . import views


urlpatterns = [
    url(r'^mineral/', include(('minerals.urls', 'minerals'), namespace='minerals')),
    url(r'^$', views.index, name='index'),
    url('admin/', admin.site.urls),
]

# Setting up urlpatterns for django-debug-toolbar(version==1.9.1)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += re_path(r'^__debug__/', include(debug_toolbar.urls)),

urlpatterns += staticfiles_urlpatterns()

mineral_catalog/minerals/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.mineral_list,
        name='mineral_list'),
    url(r'(?P<pk>\d+)/$', views.mineral_detail,
        name='mineral_detail'),
    url(r'random/', views.random_mineral,
        name='random_mineral'),
    url(r'starts_with/(?P<alpha>[a-zA-Z])/$', views.mineral_by_alphabet,
        name='mineral_alpha'),
    url(r'by_group/(?P<group>[\w ]+)/$', views.mineral_by_group,
        name='mineral_by_group'),
    url(r'by_color/(?P<color>\w+)/$', views.mineral_by_color,
        name='mineral_by_color'),
    url(r'by_crystal/(?P<crystal>\w+)/$', views.mineral_by_crystal_system,
        name='mineral_by_crystal'),
    url(r'search/$', views.mineral_search,
        name='mineral_search'),
]

mineral_catalog/minerals/models.py
from django.db import models


class Mineral(models.Model):
    """Model class with all the mineral details
        All fields has a fallback to blank attribute
    :inherit: - models.Model from django.db
    """
    name = models.CharField(max_length=255, blank=True)
    image_filename = models.CharField(max_length=255, blank=True)
    category = models.CharField(max_length=255, blank=True)
    image_caption = models.CharField(max_length=255, blank=True)
    group = models.CharField(max_length=255, blank=True)
    formula = models.CharField(max_length=255, blank=True)
    strunz_classification = models.CharField(max_length=255, blank=True)
    color = models.CharField(max_length=255, blank=True)
    crystal_system = models.CharField(max_length=255, blank=True)
    unit_cell = models.CharField(max_length=255, blank=True)
    crystal_symmetry = models.CharField(max_length=255, blank=True)
    cleavage = models.CharField(max_length=255, blank=True)
    mohs_scale_hardness = models.CharField(max_length=255, blank=True)
    luster = models.CharField(max_length=255, blank=True)
    streak = models.CharField(max_length=255, blank=True)
    diaphaneity = models.CharField(max_length=255, blank=True)
    optical_properties = models.CharField(max_length=255, blank=True)
    refractive_index = models.CharField(max_length=255, blank=True)
    crystal_habit = models.CharField(max_length=255, blank=True)
    specific_gravity = models.CharField(max_length=255, blank=True)

mineral_catalog/mineral_catalog/views.py
from django.shortcuts import Http404, render

import minerals.models


def index(request):
    """Home page view - filters name field by letter 'A'
    :parameter: - request
    :return - index.html, minerals dict startswith 'A'
    """
    try:
        minerals_set = minerals.models.Mineral.objects.filter(name__startswith="A")
    except minerals.models.Mineral.DoesNotExist:
        raise Http404
    return render(request, 'index.html', {'minerals': minerals_set})

mineral_catalog/minerals/views.py
import random

from django.db.models import Q    # , CharField  ### for mineral_search()
from django.shortcuts import Http404, render, get_object_or_404

from .models import Mineral


def mineral_by_alphabet(request, alpha):
    """Mineral by alphabet view - filters name filed by first letter
    :input: - alpha - mineral which starts with the letter alpha
    :return: - mineral_list.html + dictionary of mineral startswith alpha
    """
    try:
        # noinspection PyUnresolvedReferences
        minerals = Mineral.objects.filter(name__startswith=alpha)
    # noinspection PyUnresolvedReferences
    except Mineral.DoesNotExist:
        raise Http404
    return render(request, 'minerals/mineral_list.html',
                  {'minerals': minerals, 'alpha': alpha})


def mineral_by_color(request, color):
    """Mineral by color view - filters color field by 'color'
    :input: - color - color name
    :return: - mineral_list.html + dictionary of mineral objects
    """
    try:
        # noinspection PyUnresolvedReferences
        minerals = Mineral.objects.filter(color__icontains=color)
    except Mineral.DoesNotExist:
        raise Http404
    return render(request, 'minerals/mineral_list.html',
                  {'minerals': minerals, 'cl': color})


def mineral_by_crystal_system(request, crystal):
    """Mineral by crystal system view - filters crystal system field by
                crystal system
    :input: - crystal - crystal system name
    :return: - mineral_list.html + dictionary of mineral objects
    """
    try:
        # noinspection PyUnresolvedReferences
        minerals = Mineral.objects.filter(crystal_system__icontains=crystal)
    except Mineral.DoesNotExist:
        raise Http404

    return render(request, 'minerals/mineral_list.html',
                  {'minerals': minerals, 'cr': crystal})


def mineral_detail(request, pk):
    """Mineral detail view - filters id field by 'pk'
    :input: - pk - mineral id
    :return: - mineral_detail.html + dictionary of mineral values
    """
    # noinspection PyUnresolvedReferences
    try:
        mineral = Mineral.objects.filter(id=pk).values()[0]
    except Mineral.DoesNotExist:
        raise Http404
    return render(request, 'minerals/mineral_detail.html',
                  {'mineral': mineral})


def mineral_by_group(request, group):
    """Mineral by group view - filters group field by 'group'
    :input: - group - group name
    :return: - mineral_list.html + dictionary of mineral objects
    """
    try:
        # noinspection PyUnresolvedReferences
        minerals = Mineral.objects.filter(group=group)
    except Mineral.DoesNotExist:
        raise Http404
    return render(request, 'minerals/mineral_list.html',
                  {'minerals': minerals, 'gr': group})


def mineral_list(request):
    """Mineral list view, selects all the Mineral objects
    :return: - mineral_list.html + minerals Query
    """
    # noinspection PyUnresolvedReferences
    minerals = Mineral.objects.all()
    return render(request, 'minerals/mineral_list.html',
                  {'minerals': minerals})


def mineral_search(request):
    """Mineral search view - selects one field or multiple fields from which
                            filters the 'q' value
        request method GET, targets <input> element name attribute from layout.html
                            with value of 'q'
                            targets <select> element name attribute from layout.html
                            with value of 'mySelect'
        more in RESOURCES.txt
    :return: - mineral_list.html + dictionary of mineral queries
    """
    term = request.GET.get('q')
    field = request.GET.get('mySelect')

    # Unwanted fields list
    no_field = ['id', 'image_filename', 'image_caption']

    # If fd is not 'all' then it choose the fd value as field name
    if field != 'all':
        fields = [Mineral._meta.get_field(field)]
    else:
        # 'isinstance(field, CharField)' for selected Model type!

        # Else it choose from all fields except no_field items
        fields = [fd for fd in Mineral._meta.get_fields() if fd.name not in no_field]
    queries = [Q(**{fd.name + '__icontains': term}) for fd in fields]
    query_set = Q()
    for query in queries:
        query_set = query_set | query

    # noinspection PyUnresolvedReferences
    minerals = Mineral.objects.filter(query_set)

    return render(request, 'minerals/mineral_list.html', {'minerals': minerals})


def random_mineral(request):
    """Mineral random view, selects a random mineral
    :return: - mineral_detail.html + dictionary of random mineral values
    """
    # noinspection PyUnresolvedReferences
    minerals = Mineral.objects.all().values()
    mineral = random.choice(minerals)
    return render(request, 'minerals/mineral_detail.html',
                  {'mineral': mineral})

mineral_catalog/minerals/templates/minerals/color_list.html
{% load static %}

{% for color in colors %}
{% if cl == color %}
    <a class="font-weight-bold h6 aktiv" href="{% url 'minerals:mineral_by_color' color=color %}">
        {{ color|title }}
    </a>
{% else %}
    <a class="font-weight-normal h6 inaktiv" href="{% url 'minerals:mineral_by_color' color=color %}">
        {{ color|title }}
    </a>
{% endif %}
{% endfor %}

mineral_catalog/minerals/templates/minerals/crystal_list.html
{% load static %}

{% for crystal in crystals %}

<!-- checks which letter is selected -->
{% if cr == crystal %}
    <a class="font-weight-bold h6 aktiv" href="{% url 'minerals:mineral_by_crystal' crystal=crystal %}">
        {{ crystal|title }}
    </a>
{% else %}
    <a class="font-weight-normal h6 inaktiv" href="{% url 'minerals:mineral_by_crystal' crystal=crystal %}">
        {{ crystal|title }}
    </a>
{% endif %}
{% endfor %}

mineral_catalog/minerals/templates/minerals/group_list.html
{% load static %}

{% for group in groups %}
{% if gr == group %}
    <a class="font-weight-bold h6 aktiv" href="{% url 'minerals:mineral_by_group' group=group %}">
        {{ group }}
    </a>
{% else %}
    <a class="font-weight-normal h6 inaktiv" href="{% url 'minerals:mineral_by_group' group=group %}">
        {{ group }}
    </a>
{% endif %}
{% endfor %}

mineral_catalog/minerals/templates/minerals/mineral_detail.html
{% extends "layout.html" %}
{% load static %}
{% load extra_tags %}


{% block content %}
<div class="grid-100 mineral__container">
    <!-- Mineral Table/ Mineral Image -->
    <div class="mineral__image-bg">
        <img class="mineral__image" src="{% static 'img' %}/{{ mineral.name }}.jpg" alt="{{ mineral.name }}">
        <p class="mineral__caption">{{ mineral.image_caption }}</p>
    </div>
    <!-- Mineral name with wikipedia link -->
    <a  class="tool" data-tip="Wikipedia" href="https://en.wikipedia.org/wiki/{{ mineral.name }}" target="_blank">
        <h1 class="mineral__name mineral__detail_header">{{ mineral.name }}</h1>
    </a>
    <!-- Mineral description -->
    <div class="mineral__table-container">
        <table class="mineral__table">
            {% for field in mineral.items %}
                <!-- Checks if field exist in required field labels using check filter-->
                {% if field.0|check  %}
                    {% if field.1 != '' %}
                        <tr>
                            <td class="mineral__category">{{ field.0|title|clean_title }}</td>
                            <td>{{ field.1|safe }}</td>
                        </tr>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

mineral_catalog/minerals/templates/minerals/mineral_list.html
{% extends "layout.html" %}


{% block content %}
<!-- Minerals list -->
<div class="grid-100">
    <!-- I tried to fix the list items cut off on end of 1st column or second
    with flex property,
    the buttom part of the item continues on the next column top -->
    <ul class="minerals__container">
        {% if minerals.count != 0 %}
        {% for mineral in minerals %}
            <li class=" list-group-item">

                <!-- checks if only one mineral to center the block -->
                <a class="minerals__anchor"
                   href="{% url 'minerals:mineral_detail' pk=mineral.id %}"
                   {% if minerals.count == 1 %}
                   style="display: inline-block;"
                   {% endif %}>{{ mineral.name }}
                </a>

            </li>
        {% endfor %}

        <!-- alert message if no mineral was found -->
        {% elif minerals.count == 0 %}
            <li class=" list-group-item">
                <h3 class="minerals__anchor" style="display: inline-block;
                                             font-size: 1.7rem;
                                             color: #f35;">
                    No minerals was found with this search
                </h3>
            </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

mineral_catalog/templates/index.html
{% extends "layout.html" %}

<!-- Home page -->

 Preselected A letter alphabet list
{% block alphabet_list %}
<div  class="col-sm-12 d-flex justify-content-sm-between alph">
            {% for letter in "ABCDEFGHIJKLMNOPQRSTUVWYXZ" %}
                {% if letter == "A" %}
                    <a class="text-primary font-weight-bold h3 dis" href="{% url 'minerals:mineral_alpha' alpha=letter %}">{{ letter }}</a>
                {% else %}
                    <a class="text-white font-weight-normal h3 off" href="{% url 'minerals:mineral_alpha' alpha=letter %}">{{ letter }}</a>
                {% endif %}
            {% endfor %}
        </div>
{% endblock %}

{% block content %}
<!-- Minerals startswith A list -->
<div class="grid-100">
    <ul class="minerals__container">
        {% for mineral in minerals %}
        <li class=" list-group-item">
            <a class="minerals__anchor" href="{% url 'minerals:mineral_detail' pk=mineral.id %}">{{ mineral.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

mineral_catalog/templates/layout.html
{% load static %}
{% load extra_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Rayan's: Minerals Catalog</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
          integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body style="position: relative;">
    <!-- BACKGROUND WITH BLUR -->
    <div class="page-bg">
    </div>

    <nav class="navbar navbar-expand-md navbar-dark bg-light my-fix mb-4 py-4">
        <!-- Main logo -->
        <div class="col-sm-1 d-flex grid-100">
            <a href="{% url 'index' %}">
                <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                    <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                    <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                    <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
                </svg>
            </a>
        </div>

        <div class="col-sm-6 d-flex justify-content-sm-start">
            <a href="{% url 'minerals:mineral_list' %}">
                <h1 class="text-centered display-1 font-weight-bold tool span custom"
                    data-tip="All Minerals">Minerals
                </h1>
            </a>
        </div>
        <!--<div class="col-sm-2 d-flex  justify-content-sm-between">-->
            <!--<p class="logo__text text-centered">They are-->
                <!--<span class="tool" data-tip="Wikipedia">-->
                    <!--<a href="https://en.wikipedia.org/wiki/Sedimentary_rock"-->
                       <!--target="_blank">not rocks-->
                    <!--</a>-->
                <!--</span> but they rock-->
            <!--</p>-->
        <!--</div>-->

        <div class="col-sm-4 d-flex justify-content-end collapse navbar-collapse" id="navbarSupportedContent">
            <form method="GET" action="{% url 'minerals:mineral_search' %}"
                  name="mySelect" class="form-inline my-2 my-lg-0">

                <select name="mySelect" id="mySelect" onchange="setValue();" class="form-inline mr-sm-2 h2 frame ">
                    <option value="all" selected="">All</option>
                    <option value="name">Name</option>
                    <option value="category">Category</option>
                    <option value="group">Group</option>
                    <option value="formula">Formula</option>
                    <option value="strunz_classification">Strunz Classification</option>
                    <option value="color">Color</option>
                    <option value="crystal_system">Crystal System</option>
                    <option value="unit_cell">Unit Cell</option>
                    <option value="crystal_symmetry">Crystal Symmetry</option>
                    <option value="cleavage">Cleavage</option>
                    <option value="mohs_scale_hardness">Mohs Scale Hardness</option>
                    <option value="luster">Luster</option>
                    <option value="streak">Streak</option>
                    <option value="diaphaneity">Diaphaneity</option>
                    <option value="optical_properties">Optical Properties</option>
                    <option value="refractive_index">Refractive Index</option>
                    <option value="crystal_habit">Crystal Habit</option>
                    <option value="specific_gravity">Specific Gravity</option>
                </select>
                <input class="form-control mr-sm-2 h5 frame"
                       type="search"
                       placeholder="Search..."
                       aria-label="Search"
                       name="q">
                <button class="btn btn-outline-light my-2 my-sm-0 gomb" type="submit">&#128269;</button>

            </form>
        </div>


        <!-- ALPHABET Block, filter for mineral list -->
        {% block alphabet_list %}
        <div  class="col-sm-12 d-flex justify-content-sm-between alph">
            {% for letter in "ABCDEFGHIJKLMNOPQRSTUVWYXZ" %}
                {% if alpha == letter %}
                    <a class="text-primary font-weight-bold h3 dis" href="{% url 'minerals:mineral_alpha' alpha=letter %}">{{ letter }}</a>
                {% else %}
                    <a class="text-white font-weight-normal h3 off" href="{% url 'minerals:mineral_alpha' alpha=letter %}">{{ letter }}</a>
                {% endif %}
            {% endfor %}
        </div>
        {% endblock %}
    </nav>

    <!-- Sidebar with filter -->
    <div class="sidenav">
        <h3 class="filter_title">Filter by:</h3>
        <button class="dropdown-btn">Group</button>
        <div class="dropdown-container">
            {% group_list gr %}
        </div>

        <button class="dropdown-btn">Color</button>
        <div class="dropdown-container">
            {% color_list cl %}
        </div>

        <button class="dropdown-btn right-border">Crystal System</button>
        <div class="dropdown-container">
            {% crystal_list cr %}
        </div>
    </div>

    <div class="bounds">
        <!-- Mineral content -->
        {% block content %}{% endblock %}
    </div>

    <!-- Random mineral button -->
    <div class="minerals__random">
        <a class="minerals__anchor" href="{% url 'minerals:random_mineral' %}">Show a random mineral</a>
    </div>
<script>
/* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
var dropdown = document.getElementsByClassName("dropdown-btn");
var i;

for (i = 0; i < dropdown.length; i++) {
  dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
      dropdownContent.style.display = "none";
    } else {
      dropdownContent.style.display = "block";
    }
  });
}
</script>
</body>
</html>